/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_org_graalvm_example_JNIExample
#define _Included_org_graalvm_example_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_graalvm_example_JNIExample
 * Method:    jniCallDoingReflection
 * Signature: ()I;
 */
JNIEXPORT jint JNICALL Java_org_graalvm_example_JNIExample_jniCallDoingReflection(JNIEnv *env);

#ifdef __cplusplus
}
#endif
#endif
